[package]
name = "merino"
version = "0.1.0"
authors = ["Avery Wagar <ajmw.subs@gmail.com>"]
edition = "2018"

[dependencies]
# openssl = { version = "0.10", features = ["vendored"] }
# rayon = "1.0"
pretty_env_logger = "0.3.0"
log = "0.4.6"
structopt = "0.2"
snafu = "0.4.1"
